services:
  stackattack2-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CACHEBUST: 2
    container_name: stackattack2
    restart: unless-stopped
    networks:
      - traefik_public
    labels:
      # Traefik configuration
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_public"
      - "traefik.http.routers.stackattack2.rule=Host(`stackattack2.pusk365.ru`)"
      - "traefik.http.routers.stackattack2.entrypoints=websecure"
      - "traefik.http.routers.stackattack2.tls=true"
      - "traefik.http.routers.stackattack2.tls.certresolver=letsencrypt"
      - "traefik.http.services.stackattack2.loadbalancer.server.port=80"

networks:
  traefik_public:
    external: true
